<a href="https://colab.research.google.com/github/chandel2023/CODSOFT/blob/main/machine%20learning%20course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
print('namaste')

namaste


In [56]:
import numpy as np
import pandas as pd

In [57]:
dataset= pd.read_csv('Gujrat.csv')

In [58]:
dataset

Sl. No.                                          Indicator  ...    All India      Gujarat
0      1.00            Per Capita NSDP at 2004-05 prices (Rs.)  ...    38856.000   61220.0000
1      2.00    Growth in Per Capita NSDP at 2004-05 prices (%)  ...        2.120       6.5700
2      2.10                          Growth rate in GSDP-Total  ...        4.700       7.9600
3      2.20                    Growth rate in GSDP-Agriculture  ...        4.700       0.4500
4      2.30                       Growth rate in GSDP-Industry  ...        0.400       7.1200
5      2.40                       Growth rate in GSDP-services  ...        6.800      12.7000
6      3.00                                     Area (Sq. Km.)  ...  3287240.000  196244.0000
7      4.00                                 Population (crore)  ...      121.020       6.0400
8      5.00                   Population Density (Per Sq. Km.)  ...      368.000     308.0000
9      6.00  Decadal Growth Rate of Population (2001-2011) (%)  ...       17.600      19.3000
10     7.00                    Sex Ratio (Females/ 1000 Males)  ...      943.000     919.0000
11     8.00  Sex Ratio (0-6 years) (Female children/ 1000 m...  ...      919.000     890.0000
12     9.00                            Total Literacy Rate (%)  ...       74.000      79.3000
13     9.10                                           Male (%)  ...       82.100      87.2000
14     9.20                                         Female (%)  ...       65.500      70.7000
15    10.00                         Gender Gap in Literacy (%)  ...       16.700      16.5000
16    11.00  Infant Mortality Rate (IMR) (per 1000 live bir...  ...       40.000      36.0000
17    12.00  Maternal Mortality Rate (MMR) (per 100000 live...  ...      178.000     122.0000
18    13.00          Total Fertility Rate (TFR) (Birth/ woman)  ...        2.400       2.3000
19    14.00  Neo Natal Mortality Rate (NMR) (per 1000 live ...  ...       31.000      30.0000
20    15.00  Under 5 Mortality Rate (U-5MR) (per 1000 live ...  ...       52.000      48.0000
21    16.00                                     Birth Rate (%)  ...       21.400      20.8000
22    17.00                                     Death Rate (%)  ...        7.000       6.5000
23    18.00                           Highway Length per sq km  ...        0.023       0.0210
24    19.00                           State Highways per sq km  ...        0.050       0.0940
25    20.00        Per Capita Consumption of Electricity (kWh)  ...      914.400    1796.3000
26    21.00            Total Rail Route (km) per sq km of area  ...        0.020       0.0004
27    22.00                            Rural Tele Density (%)   ...       44.000      57.4000
28    23.00                            Urban Tele Density (%)   ...      145.500     137.6000
29    24.00    Unemployment Rate (Usual Status (adjusted)) (%)  ...        2.300       5.0000
30    25.10                    Dropout Rate: Primary Level (%)  ...        6.500       3.0000
31    25.20              Dropout Rate: Upper Primary Level (%)  ...        6.600      29.3000
32    26.11           Gross Enrolment Ratio: Primary Level (%)  ...      101.400     101.1000
33    26.12             Net Enrolment Ratio: Primary Level (%)  ...       88.100      82.9000
34    26.21     Gross Enrolment Ratio: Upper Primary Level (%)  ...       89.300      90.9000
35    26.22       Net Enrolment Ratio: Upper Primary Level (%)  ...       70.200      68.4000
36    27.00                Household availing banking services  ...       58.700      57.9000
37    28.00   Households with latrine facility within premises  ...       46.900      57.4000
38    29.00  Safe Drinking Water (Tap/Handpump/Tubewell) (%...  ...       85.500      90.3000
39    30.10                      Forest Cover (area in sq.Km.)  ...   697898.000   14653.0000
40    30.20              Forest Cover (% of geographical area)  ...       21.200       7.5000

[41 rows x 6 columns]

In [59]:
x=dataset[['All India', 'Gujarat']]

In [60]:
x

All India      Gujarat
0     38856.000   61220.0000
1         2.120       6.5700
2         4.700       7.9600
3         4.700       0.4500
4         0.400       7.1200
5         6.800      12.7000
6   3287240.000  196244.0000
7       121.020       6.0400
8       368.000     308.0000
9        17.600      19.3000
10      943.000     919.0000
11      919.000     890.0000
12       74.000      79.3000
13       82.100      87.2000
14       65.500      70.7000
15       16.700      16.5000
16       40.000      36.0000
17      178.000     122.0000
18        2.400       2.3000
19       31.000      30.0000
20       52.000      48.0000
21       21.400      20.8000
22        7.000       6.5000
23        0.023       0.0210
24        0.050       0.0940
25      914.400    1796.3000
26        0.020       0.0004
27       44.000      57.4000
28      145.500     137.6000
29        2.300       5.0000
30        6.500       3.0000
31        6.600      29.3000
32      101.400     101.1000
33       88.100      82.9000
34       89.300      90.9000
35       70.200      68.4000
36       58.700      57.9000
37       46.900      57.4000
38       85.500      90.3000
39   697898.000   14653.0000
40       21.200       7.5000

In [61]:
x=dataset[['All India','Gujarat']].values

In [62]:
x

array([[3.88560e+04, 6.12200e+04],
       [2.12000e+00, 6.57000e+00],
       [4.70000e+00, 7.96000e+00],
       [4.70000e+00, 4.50000e-01],
       [4.00000e-01, 7.12000e+00],
       [6.80000e+00, 1.27000e+01],
       [3.28724e+06, 1.96244e+05],
       [1.21020e+02, 6.04000e+00],
       [3.68000e+02, 3.08000e+02],
       [1.76000e+01, 1.93000e+01],
       [9.43000e+02, 9.19000e+02],
       [9.19000e+02, 8.90000e+02],
       [7.40000e+01, 7.93000e+01],
       [8.21000e+01, 8.72000e+01],
       [6.55000e+01, 7.07000e+01],
       [1.67000e+01, 1.65000e+01],
       [4.00000e+01, 3.60000e+01],
       [1.78000e+02, 1.22000e+02],
       [2.40000e+00, 2.30000e+00],
       [3.10000e+01, 3.00000e+01],
       [5.20000e+01, 4.80000e+01],
       [2.14000e+01, 2.08000e+01],
       [7.00000e+00, 6.50000e+00],
       [2.30000e-02, 2.10000e-02],
       [5.00000e-02, 9.40000e-02],
       [9.14400e+02, 1.79630e+03],
       [2.00000e-02, 4.00000e-04],
       [4.40000e+01, 5.74000e+01],
       [1.45500e+02,

In [63]:
y=dataset[['Source']].values

In [64]:
y

array([['CSO'],
       ['CSO'],
       ['CSO'],
       ['CSO'],
       ['CSO'],
       ['CSO'],
       ['Census'],
       ['Census'],
       ['Census'],
       ['Census'],
       ['Census'],
       ['Census'],
       ['Census'],
       ['Census'],
       ['Census'],
       ['Census'],
       ['SRS'],
       ['SRS'],
       ['SRS'],
       ['SRS'],
       ['SRS'],
       ['SRS'],
       ['SRS'],
       ['MoRTH'],
       ['MoRTH'],
       ['MoP'],
       ['MoR'],
       ['MoCIT'],
       ['MoCIT'],
       ['NSS'],
       ['DISE'],
       ['DISE'],
       ['DISE'],
       ['DISE'],
       ['DISE'],
       ['DISE'],
       ['Census'],
       ['Census'],
       ['Census'],
       ['MoEF'],
       ['MoEF']], dtype=object)

In [65]:
from sklearn.impute import SimpleImputer

In [66]:
imputer= SimpleImputer(missing_values=np.nan, strategy='mean')   #it will handle the missing values having nan

In [71]:
#imputer=imputer.fit(x[:,4:6])   #it will include the columns of x since 4 is included but 6 is not so will take indices- 4 and 5

In [73]:
#x[:,4:6]=imputer.fit_transform(x[:,4:6])   #it will replace all the mean values by the mean of the column data

In [74]:
x

array([[3.88560e+04, 6.12200e+04],
       [2.12000e+00, 6.57000e+00],
       [4.70000e+00, 7.96000e+00],
       [4.70000e+00, 4.50000e-01],
       [4.00000e-01, 7.12000e+00],
       [6.80000e+00, 1.27000e+01],
       [3.28724e+06, 1.96244e+05],
       [1.21020e+02, 6.04000e+00],
       [3.68000e+02, 3.08000e+02],
       [1.76000e+01, 1.93000e+01],
       [9.43000e+02, 9.19000e+02],
       [9.19000e+02, 8.90000e+02],
       [7.40000e+01, 7.93000e+01],
       [8.21000e+01, 8.72000e+01],
       [6.55000e+01, 7.07000e+01],
       [1.67000e+01, 1.65000e+01],
       [4.00000e+01, 3.60000e+01],
       [1.78000e+02, 1.22000e+02],
       [2.40000e+00, 2.30000e+00],
       [3.10000e+01, 3.00000e+01],
       [5.20000e+01, 4.80000e+01],
       [2.14000e+01, 2.08000e+01],
       [7.00000e+00, 6.50000e+00],
       [2.30000e-02, 2.10000e-02],
       [5.00000e-02, 9.40000e-02],
       [9.14400e+02, 1.79630e+03],
       [2.00000e-02, 4.00000e-04],
       [4.40000e+01, 5.74000e+01],
       [1.45500e+02,

In [75]:
#we have to change all the columns into numeric columns so that the operations can be performed

In [76]:
from sklearn.preprocessing import LabelEncoder

In [77]:
label_encoder_x=LabelEncoder()

In [78]:
x[:,1]=label_encoder_x.fit_transform(x[:,1])

In [79]:
x

array([[3.88560e+04, 3.80000e+01],
       [2.12000e+00, 9.00000e+00],
       [4.70000e+00, 1.20000e+01],
       [4.70000e+00, 3.00000e+00],
       [4.00000e-01, 1.00000e+01],
       [6.80000e+00, 1.30000e+01],
       [3.28724e+06, 3.90000e+01],
       [1.21020e+02, 7.00000e+00],
       [3.68000e+02, 3.30000e+01],
       [1.76000e+01, 1.50000e+01],
       [9.43000e+02, 3.50000e+01],
       [9.19000e+02, 3.40000e+01],
       [7.40000e+01, 2.50000e+01],
       [8.21000e+01, 2.70000e+01],
       [6.55000e+01, 2.40000e+01],
       [1.67000e+01, 1.40000e+01],
       [4.00000e+01, 1.90000e+01],
       [1.78000e+02, 3.10000e+01],
       [2.40000e+00, 4.00000e+00],
       [3.10000e+01, 1.80000e+01],
       [5.20000e+01, 2.00000e+01],
       [2.14000e+01, 1.60000e+01],
       [7.00000e+00, 8.00000e+00],
       [2.30000e-02, 1.00000e+00],
       [5.00000e-02, 2.00000e+00],
       [9.14400e+02, 3.60000e+01],
       [2.00000e-02, 0.00000e+00],
       [4.40000e+01, 2.10000e+01],
       [1.45500e+02,

In [80]:
# there can be some correlation between the numbers assigned for numerical data, like greater or smaller etc., to prevent this we have to do a dummy encoding having only 0,1

In [81]:
from sklearn.preprocessing import OneHotEncoder

In [82]:
onehotencoder=OneHotEncoder()

In [83]:
x=onehotencoder.fit_transform(dataset.Gujarat.values.reshape(-1,1)).toarray()

In [84]:
x

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [86]:
labelencoder_y=LabelEncoder()

In [88]:
y=labelencoder_y.fit_transform(y)

/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [89]:
y

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 9, 9, 9, 9, 9, 9,
       9, 7, 7, 5, 6, 3, 3, 8, 2, 2, 2, 2, 2, 2, 1, 1, 1, 4, 4])

In [90]:
from sklearn.model_selection import train_test_split

In [96]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)   # means 20% data will be tested and 80% data will be trained

In [97]:
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [98]:
x_test

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
   

In [99]:
y_train

array([2, 3, 9, 1, 0, 4, 9, 1, 9, 9, 1, 1, 1, 0, 9, 1, 2, 1, 2, 0, 6, 1,
       2, 7, 1, 7, 9, 9, 1, 4, 0, 0])

In [100]:
y_test

array([5, 2, 8, 0, 1, 2, 3, 1, 1])

In [101]:
#there may be some data which varies too high, so to puth them on a same scale...
from sklearn.preprocessing import StandardScaler

In [103]:
sc_x=StandardScaler()

In [105]:
x_train=sc_x.fit_transform(x_train)

In [106]:
x_test=sc_x.fit_transform(x_test)

In [107]:
x_train

array([[-0.1796053 , -0.1796053 , -0.1796053 , ..., -0.1796053 ,
        -0.1796053 , -0.1796053 ],
       [-0.1796053 , -0.1796053 , -0.1796053 , ..., -0.1796053 ,
        -0.1796053 , -0.1796053 ],
       [-0.1796053 , -0.1796053 , -0.1796053 , ..., -0.1796053 ,
        -0.1796053 , -0.1796053 ],
       ...,
       [-0.1796053 , -0.1796053 , -0.1796053 , ...,  5.56776436,
        -0.1796053 , -0.1796053 ],
       [-0.1796053 , -0.1796053 , -0.1796053 , ..., -0.1796053 ,
        -0.1796053 , -0.1796053 ],
       [-0.1796053 , -0.1796053 , -0.1796053 , ..., -0.1796053 ,
         5.56776436, -0.1796053 ]])

In [108]:
x_test

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        , -0.35355339,  0.        ,  0.        ,  0.        ,
        -0.35355339,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        , -0.35355339,  0.        ,  0.        ,
         0.        , -0.35355339, -0.35355339, -0.35355339,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        , -0.35355339,
        -0.35355339,  2.82842712,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        , -0.35355339,  0.        ,  0.        ,  0.        ,
        -0.35355339,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        , -0.35355339,  0.        ,  0.        ,
         0.        , -0.35355339, -0.35355339,  2.82842712,  0.        ,
         0.        ,  0.        ,  0.        ,  0.

In [111]:
# features are the columns heading which tells the feature of that column
# label means output we get from model after training like male, female in person column
# features and labels are very specific as per our predictions
# types of supervised ML algorithms-
# 1- regression (a- linear regression, b- polynomial regression, c- regression trees)
# 2- classification (a- random forest, b- decision trees, c- logistic regression, d- support vector machines)
# regression--- values are continuous and there is some relation between dependent and independent variables
# classification--- values are discrete/categorical/classes
# types of unsupervised ML algorithms-
# 1- clustering
# 2- association (observing some of the almost fixed combinations)
# unsupervised ML algorithms-
# a- k-means clustering, b- knn(k-nearest neighbor), c- hierarchical clustering, d- neural networks/ deep learning,
# e- single value decomposition, f- distribution models, g- principal component analysis, h- apriori algorithm
# unsupervised learning--- for complex tasks, also helps in finding patterns, also saves lot of manual work, but has less accuracy
